base: base_config/kinetics_base.yml
dataset:
  transform_type: default
#sampling
sampler:
  num_segments: [1, 1, 1, 1, 1]
  clip_length: [16, 32, 32, 64, 64]
  num_steps: [1, 1, 1, 2, 2]
  eva_num_segments: 1
  eva_num_clips: 10
  # train
  batch_size: [16, 8, 8, 4, 4]
  iter_size: [4, 8, 8, 16, 16]

network:
  # network
  net_name: p3d_resnet50
  # optimization
  pretrained_model: pretrained_weights/resnet50-19c8e357.pth
  eva_model: output/current.pth

  remove_fc: True
  transfer_weights: True
  frozen_bn: [False, False, False, True, True]

optimizer:
  # optimization
  eva_inter: False

  lr_scheduler: step
  lr_decay_epochs: [1000000]
  lr_decay_rate: 1.0

  base_learning_rate: [0.04, 0.04, 0.004, 0.0004, 0.00004]
  warmup_epoch: -1
  epochs: [58, 108, 26, 10, 18]
