dataset:
  time_dim: T
  crop_size: 224
  eva_crop_size: 256
  eva_num_crop: 3
  num_workers: 8
  transform_type: default
  no_horizontal_flip: False
  use_flow: False
  use_fore: False
  use_mixup: False

optimizer:
  warmup_multiplier: 100
  lr_scheduler: cosine
  weight_decay: 0.0001
  momentum: 0.9
  nesterov: True
  clip_gradient: 40
  loss_weight: 1.
  num_gpu: 4
  label_smooth: False
  eva_inter: True
  eva_inter_freq: 1
  fc_higher_lr: False
  adamw_solver: False

sampler:

network:
  pooling_name: PoolingAverage
  frozen_bn: False
  transfer_weights: False
  remove_fc: False
  pretrained_model: ''
  early_stride: 4

logging:
  print_freq: 10
  save_freq: 10
  output_dir: ./output
